version: '3.7'

services:
  punctuate-service:
    build: ./punctuate
    command: uvicorn punctuate.main:app --reload --host 0.0.0.0 --port 8000
    ports: 
      - 8001:8000
  grammar-service:
    build: ./grammar
    command: uvicorn grammar.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/enginx/conf.d/default.conf
    depends_on:
      - punctuate-service
      - grammar-service
